/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exchange Rates
         * @description 현재 주차 관세청 주간 고시환율 목록.
         */
        get: operations["list_exchange_rates_api_exchange_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Markets */
        get: operations["list_markets_api_admin_markets_get"];
        put?: never;
        /** Create Market */
        post: operations["create_market_api_admin_markets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market */
        get: operations["get_market_api_admin_markets__market_id__get"];
        /** Update Market */
        put: operations["update_market_api_admin_markets__market_id__put"];
        post?: never;
        /** Delete Market */
        delete: operations["delete_market_api_admin_markets__market_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets/{market_id}/product-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Product Urls
         * @description 마켓이 크롤러로 모은 상품 URL 목록(발견 원장 + 파싱 큐 상태).
         *
         *     `id`(발견 순) 오름차순으로 안정 페이지네이션. 마켓 없으면 404.
         */
        get: operations["list_product_urls_api_admin_markets__market_id__product_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 가용성 체크 (Phase 7 UptimeRobot 대상).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ExchangeRateOut
         * @description 환율 응답 계약 한 행.
         */
        ExchangeRateOut: {
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Rate Krw */
            rate_krw: string;
            /** Prev Rate Krw */
            prev_rate_krw: string | null;
            /** Rise Fall */
            rise_fall: string | null;
            /**
             * Apply Start
             * Format: date
             */
            apply_start: string;
            /**
             * Apply End
             * Format: date
             */
            apply_end: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MarketIn
         * @description 마켓 생성/수정 입력. 배송옵션은 nested(전체 동기화).
         */
        MarketIn: {
            /** Code */
            code: string;
            /** Domain */
            domain: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Country */
            country?: string | null;
            /** Language */
            language?: string | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Vat Rate
             * @default 0
             */
            vat_rate: number | string;
            /**
             * Price Includes Vat
             * @default true
             */
            price_includes_vat: boolean;
            /**
             * Local Alcohol Tax Per Liter
             * @default 0
             */
            local_alcohol_tax_per_liter: number | string;
            /**
             * Price Includes Local Alcohol Tax
             * @default false
             */
            price_includes_local_alcohol_tax: boolean;
            /**
             * Incoterm
             * @default DAP
             * @enum {string}
             */
            incoterm: "FOB" | "DAP";
            /**
             * Fta
             * @default false
             */
            fta: boolean;
            /**
             * Domestic Shipping Cost
             * @default 0
             */
            domestic_shipping_cost: number | string;
            /**
             * Crawl Ship To
             * @default KR
             */
            crawl_ship_to: string;
            /** Notes */
            notes?: string | null;
            /** Shipping Options */
            shipping_options?: components["schemas"]["ShippingOptionIn"][];
        };
        /** MarketOut */
        MarketOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Domain */
            domain: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Country */
            country: string | null;
            /** Language */
            language: string | null;
            /** Base Url */
            base_url: string | null;
            /** Active */
            active: boolean;
            /** Vat Rate */
            vat_rate: string;
            /** Price Includes Vat */
            price_includes_vat: boolean;
            /** Local Alcohol Tax Per Liter */
            local_alcohol_tax_per_liter: string;
            /** Price Includes Local Alcohol Tax */
            price_includes_local_alcohol_tax: boolean;
            /** Incoterm */
            incoterm: string;
            /** Fta */
            fta: boolean;
            /** Domestic Shipping Cost */
            domestic_shipping_cost: string;
            /** Crawl Ship To */
            crawl_ship_to: string;
            /** Notes */
            notes: string | null;
            /** Shipping Options */
            shipping_options: components["schemas"]["ShippingOptionOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProductUrlOut
         * @description 크롤러 ①이 모은 상품 URL 1건(발견 원장 + ②단계 파싱 커서).
         */
        ProductUrlOut: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Name */
            name: string | null;
            /** Stock Status */
            stock_status: string | null;
            /** Available */
            available: boolean;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Last Parsed At */
            last_parsed_at: string | null;
        };
        /** ShippingOptionIn */
        ShippingOptionIn: {
            /** Name */
            name: string;
            /** Cost */
            cost: number | string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** ShippingOptionOut */
        ShippingOptionOut: {
            /** Name */
            name: string;
            /** Cost */
            cost: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_exchange_rates_api_exchange_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateOut"][];
                };
            };
        };
    };
    list_markets_api_admin_markets_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_market_api_admin_markets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_api_admin_markets__market_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_market_api_admin_markets__market_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_market_api_admin_markets__market_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_urls_api_admin_markets__market_id__product_urls_get: {
        parameters: {
            query?: {
                /** @description 재고 가용 여부 필터 */
                available?: boolean | null;
                /** @description 파싱 상태 필터 */
                parse_status?: ("pending" | "ok" | "error" | "skipped") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductUrlOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
