/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exchange Rates
         * @description 현재 주차 관세청 주간 고시환율 목록.
         */
        get: operations["list_exchange_rates_api_exchange_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Markets */
        get: operations["list_markets_api_admin_markets_get"];
        put?: never;
        /** Create Market */
        post: operations["create_market_api_admin_markets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market */
        get: operations["get_market_api_admin_markets__market_id__get"];
        /** Update Market */
        put: operations["update_market_api_admin_markets__market_id__put"];
        post?: never;
        /** Delete Market */
        delete: operations["delete_market_api_admin_markets__market_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets/{market_id}/product-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Product Urls
         * @description 마켓이 크롤러로 모은 상품 URL 목록(발견 원장 + 파싱 큐 상태).
         *
         *     `id`(발견 순) 오름차순으로 안정 페이지네이션. 마켓 없으면 404.
         */
        get: operations["list_product_urls_api_admin_markets__market_id__product_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/markets/{market_id}/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Crawl
         * @description 마켓의 상품 URL 크롤을 **비동기로 트리거**(관리 UI 버튼용).
         *
         *     크롤은 robots Crawl-delay(사이트별)로 길어질 수 있어 동기 실행하지 않고 Celery로
         *     enqueue하고 즉시 202+`task_id`를 반환한다. 실제 수집·UPSERT는 워커(크롤러 ①)가 수행.
         *
         *     가드(handoff-api-crawl-trigger):
         *     - 어댑터 없는 마켓 → 400, 없는 마켓 → 404.
         *     - 이미 진행 중(Redis 락 보유)이면 → 409 (연타 시 큐 쌓임 방지). 최종 보장은 워커의 태스크 락.
         */
        post: operations["trigger_crawl_api_admin_markets__market_id__crawl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/crawl/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Jobs
         * @description 진행 중인 모든 크롤 잡(요구사항 #1). 워커가 없거나 응답이 없으면 빈 목록.
         */
        get: operations["list_active_jobs_api_admin_crawl_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/crawl/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedule
         * @description 등록된 정기 크롤 스케줄 목록(요구사항 #3). beat 정적 정의에서 읽는다.
         */
        get: operations["list_schedule_api_admin_crawl_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/crawl/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description 완료/진행 크롤 잡 이력(요구사항 #2) — 최근 실행 순(id 내림차순).
         *
         *     각 행에 실행 시각(`started_at`)·완료 시각(`finished_at`)·상태·적재 건수가 담긴다.
         *     워커의 Celery signals(`crawl_ledger`)가 적재한 `crawl_jobs` 원장을 조회한다.
         */
        get: operations["list_history_api_admin_crawl_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/crawl/jobs/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description 단일 크롤 잡 상태/결과(트리거 후 폴링용). 결과 백엔드에서 조회.
         */
        get: operations["get_job_status_api_admin_crawl_jobs__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/crawl/jobs/{task_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Job
         * @description 진행 중인 크롤 잡 종료(요구사항 #4).
         *
         *     `terminate=True`면 실행 중 워커 프로세스에 SIGTERM을 보내 즉시 중단,
         *     `False`면 아직 시작 안 한 잡만 취소(실행 중인 건 두고 재실행 방지). 비동기 fire-and-forget.
         */
        post: operations["revoke_job_api_admin_crawl_jobs__task_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 가용성 체크 (Phase 7 UptimeRobot 대상).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveJob
         * @description 진행 중인 크롤 잡 1건(워커에서 실행 중).
         */
        ActiveJob: {
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            /**
             * Args
             * @default []
             */
            args: unknown[];
            /**
             * Kwargs
             * @default {}
             */
            kwargs: Record<string, never>;
            /** Worker */
            worker: string;
            /** Started At */
            started_at?: string | null;
        };
        /**
         * CrawlIn
         * @description 크롤 트리거 옵션. `max_pages`로 스모크(예: 1페이지=24건)만 돌릴 수 있다.
         */
        CrawlIn: {
            /** Max Pages */
            max_pages?: number | null;
        };
        /**
         * CrawlJobOut
         * @description 완료/진행 크롤 잡 이력 1건(`crawl_jobs` 원장).
         */
        CrawlJobOut: {
            /** Id */
            id: number;
            /** Task Id */
            task_id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string | null;
            /** Status */
            status: string;
            /** Args */
            args: string | null;
            /** Result Count */
            result_count: number | null;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CrawlTriggerOut
         * @description 크롤 트리거 응답 — 비동기 enqueue 결과(즉시 반환).
         */
        CrawlTriggerOut: {
            /** Task Id */
            task_id: string;
            /** Market Id */
            market_id: number;
            /** Domain */
            domain: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * ExchangeRateOut
         * @description 환율 응답 계약 한 행.
         */
        ExchangeRateOut: {
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Rate Krw */
            rate_krw: string;
            /** Prev Rate Krw */
            prev_rate_krw: string | null;
            /** Rise Fall */
            rise_fall: string | null;
            /**
             * Apply Start
             * Format: date
             */
            apply_start: string;
            /**
             * Apply End
             * Format: date
             */
            apply_end: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatusOut */
        JobStatusOut: {
            /** Task Id */
            task_id: string;
            /** State */
            state: string;
            /** Result */
            result?: unknown | null;
        };
        /**
         * MarketIn
         * @description 마켓 생성/수정 입력. 배송옵션은 nested(전체 동기화).
         */
        MarketIn: {
            /** Code */
            code: string;
            /** Domain */
            domain: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Country */
            country?: string | null;
            /** Language */
            language?: string | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Vat Rate
             * @default 0
             */
            vat_rate: number | string;
            /**
             * Price Includes Vat
             * @default true
             */
            price_includes_vat: boolean;
            /**
             * Local Alcohol Tax Per Liter
             * @default 0
             */
            local_alcohol_tax_per_liter: number | string;
            /**
             * Price Includes Local Alcohol Tax
             * @default false
             */
            price_includes_local_alcohol_tax: boolean;
            /**
             * Incoterm
             * @default DAP
             * @enum {string}
             */
            incoterm: "FOB" | "DAP";
            /**
             * Fta
             * @default false
             */
            fta: boolean;
            /**
             * Domestic Shipping Cost
             * @default 0
             */
            domestic_shipping_cost: number | string;
            /**
             * Crawl Ship To
             * @default KR
             */
            crawl_ship_to: string;
            /** Notes */
            notes?: string | null;
            /** Shipping Options */
            shipping_options?: components["schemas"]["ShippingOptionIn"][];
        };
        /** MarketOut */
        MarketOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Domain */
            domain: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Country */
            country: string | null;
            /** Language */
            language: string | null;
            /** Base Url */
            base_url: string | null;
            /** Active */
            active: boolean;
            /** Vat Rate */
            vat_rate: string;
            /** Price Includes Vat */
            price_includes_vat: boolean;
            /** Local Alcohol Tax Per Liter */
            local_alcohol_tax_per_liter: string;
            /** Price Includes Local Alcohol Tax */
            price_includes_local_alcohol_tax: boolean;
            /** Incoterm */
            incoterm: string;
            /** Fta */
            fta: boolean;
            /** Domestic Shipping Cost */
            domestic_shipping_cost: string;
            /** Crawl Ship To */
            crawl_ship_to: string;
            /** Notes */
            notes: string | null;
            /** Shipping Options */
            shipping_options: components["schemas"]["ShippingOptionOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProductUrlOut
         * @description 크롤러 ①이 모은 상품 URL 1건(발견 원장 + ②단계 파싱 커서).
         */
        ProductUrlOut: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Name */
            name: string | null;
            /** Stock Status */
            stock_status: string | null;
            /** Available */
            available: boolean;
            /** Parse Status */
            parse_status: string;
            /** Parse Error */
            parse_error: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Last Parsed At */
            last_parsed_at: string | null;
        };
        /** RevokeOut */
        RevokeOut: {
            /** Task Id */
            task_id: string;
            /**
             * Revoked
             * @default true
             */
            revoked: boolean;
            /** Terminated */
            terminated: boolean;
        };
        /**
         * ScheduleEntry
         * @description beat 스케줄 1건(정기 크롤 예정).
         */
        ScheduleEntry: {
            /** Name */
            name: string;
            /** Task */
            task: string;
            /** Schedule */
            schedule: string;
        };
        /** ShippingOptionIn */
        ShippingOptionIn: {
            /** Name */
            name: string;
            /** Cost */
            cost: number | string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** ShippingOptionOut */
        ShippingOptionOut: {
            /** Name */
            name: string;
            /** Cost */
            cost: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_exchange_rates_api_exchange_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateOut"][];
                };
            };
        };
    };
    list_markets_api_admin_markets_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_market_api_admin_markets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_api_admin_markets__market_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_market_api_admin_markets__market_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_market_api_admin_markets__market_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_urls_api_admin_markets__market_id__product_urls_get: {
        parameters: {
            query?: {
                /** @description 재고 가용 여부 필터 */
                available?: boolean | null;
                /** @description 파싱 상태 필터 */
                parse_status?: ("pending" | "ok" | "error" | "skipped") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductUrlOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_crawl_api_admin_markets__market_id__crawl_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                market_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlTriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_jobs_api_admin_crawl_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedule_api_admin_crawl_schedule_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_admin_crawl_history_get: {
        parameters: {
            query?: {
                /** @description 도메인 필터 */
                domain?: string | null;
                /** @description 상태 필터 */
                status?: ("running" | "success" | "failure" | "revoked") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_admin_crawl_jobs__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_job_api_admin_crawl_jobs__task_id__revoke_post: {
        parameters: {
            query?: {
                terminate?: boolean;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
